// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string event_playTime = "CgkIyvat1Z0MEAIQCg"; // <GPGSID>
        public const string achievement_upgrade = "CgkIyvat1Z0MEAIQCQ"; // <GPGSID>
        public const string achievement_tutorial = "CgkIyvat1Z0MEAIQAQ"; // <GPGSID>
        public const string achievement_clear3 = "CgkIyvat1Z0MEAIQAg"; // <GPGSID>
        public const string achievement_shopper = "CgkIyvat1Z0MEAIQBQ"; // <GPGSID>
        public const string leaderboard_flags = "CgkIyvat1Z0MEAIQCw"; // <GPGSID>
        public const string achievement_defeat = "CgkIyvat1Z0MEAIQCA"; // <GPGSID>
        public const string achievement_stars3 = "CgkIyvat1Z0MEAIQBw"; // <GPGSID>
        public const string achievement_clear5 = "CgkIyvat1Z0MEAIQAw"; // <GPGSID>
        public const string achievement_clear7 = "CgkIyvat1Z0MEAIQBA"; // <GPGSID>

}

